config/routes.rb
Rails.application.routes.draw do
  resources :pages
  resources :events
  
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # root route at external/home
  root 'external#home'

  get '/users/auth/:provider/callback' => 'sessions#create'
  get '/users/auth/failure', to: redirect('/users/sign_in')
  get '/users', to: redirect('/users/sign_up')

  # external page routes
  get '/about', to: 'external#about'
  get '/contact', to: 'external#contact'
  get '/view_events', to: 'external#events'
  get '/home', to: 'external#home'
  get '/faq', to: 'external#faq'

  # internal page routes
  match '/attend', to: 'internal#attend', :via => :all
  match '/profile', to: 'internal#profile', :via => :all
  match '/internal_contact', to: 'internal#internal_contact', :via => :all

  # internal actions
  post 'attend_event', to: 'events#attend_event'
  get '/search', to: "internal#search"
  
  # admin page routes
  get '/manage_members', to: 'admin#manage_members'
  get '/manage_pages', to: 'admin#manage_pages'
  get '/update_points', to: 'admin#update_points_page'

  # admin actions
  get '/make_user_admin/:userid', to: 'admin#make_user_admin'
  get '/make_user_member/:userid', to: 'admin#make_user_member'
  get '/make_user_alumni/:userid', to: 'admin#make_user_alumni'
  get '/remove_user_member/:userid', to: 'admin#remove_user_member'
  get '/show_user_attendance/:userid', to: 'admin#show_user_attendance'
  get '/delete_user/:userid', to: 'admin#delete_user'
  get '/remove_points_type/:points_type_id', to: 'admin#remove_points_type'
  post '/show_user_attendance/change_user_points', to: 'admin#change_user_points'
  post '/change_points_type', to: 'admin#change_points_type'

  get '/events/show_attendance/:event_id', to: 'events#show_attendance'
  get '/events/remove_from_attendance/:event_id/:uid', to: 'events#remove_from_attendance'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  validates :event_name, presence: true
  validates :description, presence: true
  validates :passcode, presence: true
  validates :date, presence: true
  validates :points, presence: true

  after_destroy do |this_event|
    AttendanceRecord.where(event_id: this_event.id).delete_all
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]
  before_action :check_has_admin_access, only: %i[index show new edit create update destroy show_attendance remove_from_attendance]
  before_action :check_has_member_access, only: %i[attend_event]

  # GET /events or /events.json
  def index
    # order events by date
    @events_today = Event.where(date: Time.zone.today.all_day).order('date ASC')
    @upcoming_events = Event.order('date ASC').where('date > ?', Time.zone.now.end_of_day)
    @past_events = Event.order('date DESC').where('date < ?', Time.zone.now.beginning_of_day)
  end

  # POST /events/1/attend_event/password
  def attend_event
    this_event = Event.find(params[:event_id])
    if this_event.passcode == params[:password]
      new_record = AttendanceRecord.create!(event_id: this_event.id, uid: current_user.id, date_log: DateTime.now, event_name: this_event.event_name,
                                            member_name: current_user.full_name
      )
      new_record.save!
      new_score = this_event.points + UserScore.where(user_id: current_user.id, points_type_id: this_event.points_type_id).first.score
      ActiveRecord::Base.connection.execute("UPDATE user_scores SET score = #{new_score} WHERE user_id = #{current_user.id} AND points_type_id = #{this_event.points_type_id};")
      flash.notice = 'Attended event!'
    else
      flash.notice = 'Incorrect password.'
    end
    redirect_to('/attend')
  end

  # GET events/remove_from_attendance/1/2
  def remove_from_attendance
    if !params[:event_id] || !params[:uid]
      flash.notice = 'Error: event or user not specified.'
      redirect_to('/events')
    else
      this_record = AttendanceRecord.where(event_id: params[:event_id], uid: params[:uid]).first
      if this_record
        this_event = Event.find(this_record.event_id)
        this_user = User.find(this_record.uid)
        new_score = this_event.points - UserScore.where(user_id: this_user.id, points_type_id: this_event.points_type_id).first.score
        ActiveRecord::Base.connection.execute("UPDATE user_scores SET score = #{new_score} WHERE user_id = #{this_user.id} AND points_type_id = #{this_event.points_type_id};")
        member_name = this_record.member_name
        AttendanceRecord.where(event_id: params[:event_id], uid: params[:uid]).delete_all
        flash.notice = "Member #{member_name} has been successfully removed from event."
        redirect_to("/events/show_attendance/#{params[:event_id]}")
      else
        flash.notice = 'Error: event or user not found.'
        redirect_to('/events')
      end
    end
  end

  # GET /events/1 or /events/1.json
  def show; end

  # GET /events/show_attendance/1
  def show_attendance
    @this_event = Event.find(params[:event_id])
    @records = AttendanceRecord.where(event_id: @this_event.id)
  end

  # GET /events/new
  def new
    @event = Event.new
    @points_types = PointsType.all.order('id ASC')
    @can_edit_points = !AttendanceRecord.where(event_id: @event.id).count.positive?
  end

  # GET /events/1/edit
  def edit
    @points_types = PointsType.all.order('id ASC')
    @can_edit_points = !AttendanceRecord.where(event_id: @event.id).count.positive?
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)
    @points_types = PointsType.all.order('id ASC')
    @can_edit_points = !AttendanceRecord.where(event_id: @event.id).count.positive?

    respond_to do |format|
      if @event.save
        format.html { redirect_to(event_url(@event), notice: 'Event was successfully created.') }
        format.json { render(:show, status: :created, location: @event) }
      else
        format.html { render(:new, status: :unprocessable_entity) }
        format.json { render(json: @event.errors, status: :unprocessable_entity) }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    @points_types = PointsType.all.order('id ASC')
    @can_edit_points = !AttendanceRecord.where(event_id: @event.id).count.positive?
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to(event_url(@event), notice: 'Event was successfully updated.') }
        format.json { render(:show, status: :ok, location: @event) }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
        format.json { render(json: @event.errors, status: :unprocessable_entity) }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    # TODO: add confirmation message
    @event.destroy!

    respond_to do |format|
      format.html { redirect_to(events_url, notice: 'Event was successfully deleted.') }
      format.json { head(:no_content) }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:event_name, :description, :passcode, :date, :points_type_id, :points)
  end

  def check_has_admin_access
    return true if admin?

    flash.alert = 'You do not have permission to access this.'
    redirect_to(home_path)
    false
  end

  def check_has_member_access
    return true if member?

    flash.alert = 'You do not have permission to access this.'
    redirect_to(home_path)
    false
  end
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :event_name %>
    <%= form.text_field :event_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4 %>
  </div>

  <div class="field">
    <%= form.label :passcode %>
    <%= form.text_field :passcode %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_field :date %>
  </div>
  
  <% if @can_edit_points %>
    <div class="field">
      <%= form.label :points_type_id, "Points Type" %>
      <%= form.select :points_type_id, options_from_collection_for_select(@points_types, 'id', 'name', event.points_type_id || 1) %>
    </div>

    <div class="field">
      <%= form.label :points %>
      <%= form.number_field :points, :value => event.points || 1 %>
    </div>
  <% else %>
    <div class="field">
      <%= form.label :points_type_id, "Points Type: #{get_points_type(event.points_type_id)}" %>
    </div>

    <div class="field">
      <%= form.label :points, "Points: #{event.points}" %>
    </div>

    <div class="field">
      <%= form.label "points-notice", "Note: you cannot change the points for this event because there are members in attendance for this event." %>
    </div>
  <% end %>

  <div class="actions center">
    <%= form.submit :class => 'pink_button' %>
  </div>
<% end %>

app/views/events/delete.html.erb
<h1>Events#delete</h1>
<p>Find me in app/views/events/delete.html.erb</p>

app/views/events/edit.html.erb
<%= stylesheet_link_tag "events" %>

<body>
  <div class="container">
    <div class="box narrow">
      <div class="center">
        <h1>Editing Event</h1>

        <%= render 'form', event: @event %>
        <%= link_to 'Delete Event', event_path(@event), method: :delete, class: 'black_button' %>
        <p>
          <%= link_to 'Show', @event %> |
          <%= link_to 'Back', events_path %>
        </p>
      </div>
    </div>
  </div>
</body>

app/views/events/index.html.erb
<%= stylesheet_link_tag "events" %>

<body>
  <div class="container">
    <div class="box">
      <p>
      <%= link_to 'New Event', new_event_path, class: "pink_button link_button" %>
      &ensp;
      <%= link_to 'Update Points Types', '/update_points', class: "black_button link_button" %>
      </p>


      <h1>Events Today</h1>
      <%= @current_time %>
      <%= @print_time %>

      <% if @events_today.length > 0 %>
        <div class="events_container">
          <% @events_today.each do |event| %>
            <%= render :partial => 'shared/event_card', :locals => {
              :event_id => event.id,
              :event_name => event.event_name,
              :event_date => event.date,
              :points_type_id => event.points_type_id,
              :event_description => event.description,
              :show_passcode => event.passcode,
              :is_attend => false,
              :is_admin => true
              } %>
          <% end %>
        </div>
      <% else %>
        <p>No events today.</p>
      <% end %>

      <h1>Upcoming Events</h1>

      <% if @upcoming_events.length > 0 %>
        <div class="events_container">
          <% @upcoming_events.each do |event| %>
            <%= render :partial => 'shared/event_card', :locals => {
              :event_id => event.id,
              :event_name => event.event_name,
              :event_date => event.date,
              :points_type_id => event.points_type_id,
              :event_description => event.description,
              :show_passcode => event.passcode,
              :is_attend => false,
              :is_admin => true
              } %>
          <% end %>
        </div>
      <% else %>
        <p>No upcoming events.</p>
      <% end %>

      <br>

      <h1>Past Events</h1>
      <% if @past_events.length > 0 %>
        <div class="events_container">
          <% @past_events.each do |event| %>
            <%= render :partial => 'shared/event_card', :locals => {
              :event_id => event.id,
              :event_name => event.event_name,
              :event_date => event.date,
              :points_type_id => event.points_type_id,
              :event_description => event.description,
              :show_passcode => event.passcode,
              :is_attend => false,
              :is_admin => true
              } %>
          <% end %>
        </div>
      <% else %>
        <p>No past events.</p>
      <% end %>
    </div>
  </div>
</body>

app/views/events/new.html.erb
<%= stylesheet_link_tag "events" %>

<body>
  <div class="container">
    <div class="box narrow">
      <div class="center">
        <h1>New Event</h1>

        <%= render 'form', event: @event %>

        <%= link_to 'Back', events_path, class: 'black_button' %>
      </div>
    </div>
  </div>
</body>

app/views/events/show.html.erb
<%= stylesheet_link_tag "events" %>

<body>
  <div class="container">
    <div class="box narrow show_event">
      <h1>Event Details</h1>

      <p id="notice"><%= notice %></p>

      <p>
        <strong>Event name:</strong>
        <%= @event.event_name %>
      </p>

      <p>
        <strong>Description:</strong>
        <%= @event.description %>
      </p>

      <p>
        <strong>Passcode:</strong>
        <%= @event.passcode %>
      </p>

      <p>
        <strong>Date:</strong>
        <%= @event.date %>
      </p>

      <p>
        <strong>Points Type:</strong>
        <%= get_points_type(@event.points_type_id) %>
      </p>

      <p>
        <strong>Points:</strong>
        <%= @event.points %>
      </p>

      <%= link_to 'Edit', edit_event_path(@event) %>
      |
      <%= link_to 'Back', events_path %>
    </div>
  </div>
</body>

app/views/events/show_attendance.html.erb
<%= stylesheet_link_tag "attendance" %>

<body>
  <div class="container">
    <div class="box">
      <h1>Attendance Record</h1>
      <div class="events_container">
        <%= render :partial => 'shared/event_card', :locals => {
          :event_id => @this_event.id,
          :event_name => @this_event.event_name,
          :event_date => @this_event.date,
          :points_type_id => @this_event.points_type_id,
          :event_description => @this_event.description,
          :show_passcode => nil,
          :is_attend => false,
          :is_admin => false
        } %>
      </div>

      <% if @records.length > 0 %>
        <h3>Members in attendance:</h3>
        <table class="user_table">
          <thead>
            <th>Name</th>
            <th>Time of attendance</th>
            <th></th>
          </thead>
          <% @records.each do |record| %>
            <tr id=<%= "attendance_row_#{record.uid}"%>>
              <td><%= record.member_name %></td>
              <td><%= record.date_log.to_formatted_s(:get_time) %>
              <td><%= link_to 'Remove', "/events/remove_from_attendance/#{record.event_id}/#{record.uid}", class: 'remove_link' %></td>
            </tr>
          <% end %>
        </table>
      <% else %>
        <p>No one has attended this event yet.</p>
      <% end %>

      <%= link_to 'Back', events_path, class: 'black_button' %>
    </div>
  </div>
</body>