config/routes.rb
Rails.application.routes.draw do
  resources :pages
  resources :events
  
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # root route at external/home
  root 'external#home'

  get '/users/auth/:provider/callback' => 'sessions#create'
  get '/users/auth/failure', to: redirect('/users/sign_in')
  get '/users', to: redirect('/users/sign_up')

  # external page routes
  get '/about', to: 'external#about'
  get '/contact', to: 'external#contact'
  get '/view_events', to: 'external#events'
  get '/home', to: 'external#home'
  get '/faq', to: 'external#faq'

  # internal page routes
  match '/attend', to: 'internal#attend', :via => :all
  match '/profile', to: 'internal#profile', :via => :all
  match '/internal_contact', to: 'internal#internal_contact', :via => :all

  # internal actions
  post 'attend_event', to: 'events#attend_event'
  get '/search', to: "internal#search"
  
  # admin page routes
  get '/manage_members', to: 'admin#manage_members'
  get '/manage_pages', to: 'admin#manage_pages'
  get '/update_points', to: 'admin#update_points_page'

  # admin actions
  get '/make_user_admin/:userid', to: 'admin#make_user_admin'
  get '/make_user_member/:userid', to: 'admin#make_user_member'
  get '/make_user_alumni/:userid', to: 'admin#make_user_alumni'
  get '/remove_user_member/:userid', to: 'admin#remove_user_member'
  get '/show_user_attendance/:userid', to: 'admin#show_user_attendance'
  get '/delete_user/:userid', to: 'admin#delete_user'
  get '/remove_points_type/:points_type_id', to: 'admin#remove_points_type'
  post '/show_user_attendance/change_user_points', to: 'admin#change_user_points'
  post '/change_points_type', to: 'admin#change_points_type'

  get '/events/show_attendance/:event_id', to: 'events#show_attendance'
  get '/events/remove_from_attendance/:event_id/:uid', to: 'events#remove_from_attendance'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_attendance, only: %i[ show edit update destroy ]

  # GET /attendances or /attendances.json
  def index
    @attendances = Attendance.all
  end

  # GET /attendances/1 or /attendances/1.json
  def show
  end

  # GET /attendances/new
  def new
    @attendance = Attendance.new
  end

  # GET /attendances/1/edit
  def edit
  end

  # POST /attendances or /attendances.json
  def create
    @attendance = Attendance.new(attendance_params)

    respond_to do |format|
      if @attendance.save
        format.html { redirect_to attendance_url(@attendance), notice: "Attendance was successfully created." }
        format.json { render :show, status: :created, location: @attendance }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendances/1 or /attendances/1.json
  def update
    respond_to do |format|
      if @attendance.update(attendance_params)
        format.html { redirect_to attendance_url(@attendance), notice: "Attendance was successfully updated." }
        format.json { render :show, status: :ok, location: @attendance }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendances/1 or /attendances/1.json
  def destroy
    @attendance.destroy

    respond_to do |format|
      format.html { redirect_to attendances_url, notice: "Attendance was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendance
      @attendance = Attendance.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def attendance_params
      params.require(:attendance).permit(:event_id, :member_id, :date_log, :event_name)
    end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/views/attendances/_form.html.erb
<%= form_with(model: attendance) do |form| %>
  <% if attendance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attendance.errors.count, "error") %> prohibited this attendance from being saved:</h2>

      <ul>
        <% attendance.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :event_id %>
    <%= form.number_field :event_id %>
  </div>

  <div class="field">
    <%= form.label :member_id %>
    <%= form.number_field :member_id %>
  </div>

  <div class="field">
    <%= form.label :date_log %>
    <%= form.date_select :date_log %>
  </div>

  <div class="field">
    <%= form.label :event_name %>
    <%= form.text_field :event_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/attendances/edit.html.erb
<h1>Editing Attendance</h1>

<%= render 'form', attendance: @attendance %>

<%= link_to 'Show', @attendance %> |
<%= link_to 'Back', attendances_path %>

app/views/attendances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Attendances</h1>

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>Member</th>
      <th>Date log</th>
      <th>Event name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attendances.each do |attendance| %>
      <tr>
        <td><%= attendance.event_id %></td>
        <td><%= attendance.member_id %></td>
        <td><%= attendance.date_log %></td>
        <td><%= attendance.event_name %></td>
        <td><%= link_to 'Show', attendance %></td>
        <td><%= link_to 'Edit', edit_attendance_path(attendance) %></td>
        <td><%= link_to 'Destroy', attendance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attendance', new_attendance_path %>

app/views/attendances/new.html.erb
<h1>New Attendance</h1>

<%= render 'form', attendance: @attendance %>

<%= link_to 'Back', attendances_path %>

app/views/attendances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event:</strong>
  <%= @attendance.event_id %>
</p>

<p>
  <strong>Member:</strong>
  <%= @attendance.member_id %>
</p>

<p>
  <strong>Date log:</strong>
  <%= @attendance.date_log %>
</p>

<p>
  <strong>Event name:</strong>
  <%= @attendance.event_name %>
</p>

<%= link_to 'Edit', edit_attendance_path(@attendance) %> |
<%= link_to 'Back', attendances_path %>